// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJH2GM9ZtiRDR-Kt6Pcm3Fu27Q1yooWM',
    appId: '1:926289066376:web:974cbc5cf73cb03b52e23d',
    messagingSenderId: '926289066376',
    projectId: 'teacherapp-49ef9',
    authDomain: 'teacherapp-49ef9.firebaseapp.com',
    storageBucket: 'teacherapp-49ef9.firebasestorage.app',
    measurementId: 'G-X8GPYMC5E6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYy4eEZMcJncaOwlwlKI42DSPKCcmW6N8',
    appId: '1:926289066376:ios:b6f9d37dedaac43452e23d',
    messagingSenderId: '926289066376',
    projectId: 'teacherapp-49ef9',
    storageBucket: 'teacherapp-49ef9.firebasestorage.app',
    iosBundleId: 'com.example.teacherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYy4eEZMcJncaOwlwlKI42DSPKCcmW6N8',
    appId: '1:926289066376:ios:b6f9d37dedaac43452e23d',
    messagingSenderId: '926289066376',
    projectId: 'teacherapp-49ef9',
    storageBucket: 'teacherapp-49ef9.firebasestorage.app',
    iosBundleId: 'com.example.teacherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJH2GM9ZtiRDR-Kt6Pcm3Fu27Q1yooWM',
    appId: '1:926289066376:web:287d53d38a14873f52e23d',
    messagingSenderId: '926289066376',
    projectId: 'teacherapp-49ef9',
    authDomain: 'teacherapp-49ef9.firebaseapp.com',
    storageBucket: 'teacherapp-49ef9.firebasestorage.app',
    measurementId: 'G-JB8S346RWQ',
  );
}
